In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, r2_score

from sklearn.linear_model import Ridge, Lasso, ElasticNet, LinearRegression

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler

from sklearn.compose import ColumnTransformer,make_column_selector

In [ ]:
imputer = SimpleImputer(strategy='mean').set_output(transform='pandas')
imputer.fit(job) # calculates mean of every column , can use anything like 
imputer.statistics_

imputer.transform(job)

#Replace missing values using a descriptive statistic (e.g. mean, median, or most frequent) along each column, or using a constant value.

In [3]:
a = np.array([[34, 678, 0.4],
              [45, 786, 0.6],
              [49, 893, 0.9],
              [58, 700, 0.1]])
df = pd.DataFrame(a, columns=['X1','X2','X3'])
df

     X1     X2   X3
0  34.0  678.0  0.4
1  45.0  786.0  0.6
2  49.0  893.0  0.9
3  58.0  700.0  0.1

In [4]:
df['X1'].mean(), df['X1'].std()

(46.5, 9.9498743710662)

In [7]:
scaler = StandardScaler().set_output(transform='pandas')
scaler.fit(df) # computes mean and sd of every column

df_scl = scaler.transform(df)
df_scl

         X1        X2        X3
0 -1.450647 -1.019715 -0.342997
1 -0.174078  0.257146  0.342997
2  0.290129  1.522184  1.371989
3  1.334595 -0.759614 -1.371989

In [9]:
scaler = MinMaxScaler().set_output(transform='pandas')
scaler.fit(df) # computes Min and Max of every column

df_scl = scaler.transform(df)
df_scl

         X1        X2     X3
0  0.000000  0.000000  0.375
1  0.458333  0.502326  0.625
2  0.625000  1.000000  1.000
3  1.000000  0.102326  0.000

In [ ]:
lr =LabelEncoder()
y_train=lr.fit_transform(y_train)
y_test=lr.transform(y_test)

oe=OrdinalEncoder()
sc=StandardScaler()
ohe=OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')

trans = ColumnTransformer(transformers=[('OHE',ohe,make_column_selector(dtype_include=['object'])),('SC',sc,['tenure','MonthlyCharges','TotalCharges'])],
                         remainder='passthrough',verbose_feature_names_out=False).set_output(transform='pandas')

X_tran_train=trans.fit_transform(X_train)
X_test_trans=trans.transform(X_test)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.3, 
    random_state=26
)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

poly = PolynomialFeatures(degree=2) #can change degree
X_poly = poly.fit_transform(X)

poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform='pandas')

alphas = [0.001, 0.01, 0.1, 0.5, 1, 1.5, 2 , 2,5 , 5, 10]
scores = []
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train, y_train)
    y_pred = ridge.predict(X_test)
    scores.append([a, mean_absolute_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha', 'error'])
df_scores.sort_values('error')

alphas = [0.001, 0.01, 0.1, 0.5, 1, 1.5, 2 , 2,5 , 5, 10]
scores = []
for a in alphas:
    lasso = Lasso(alpha=a)
    lasso.fit(X_train, y_train)
    y_pred = lasso.predict(X_test)
    scores.append([a, mean_absolute_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha', 'error'])
df_scores.sort_values('error')


alphas = [0.001, 0.01, 0.1, 0.5, 1, 1.5, 2 , 2,5 , 5, 10]
ratios = [0.001, 0.25, 0.5, 0.75, 1]
scores = []
for a in alphas:
    for r in ratios:
        elastic = ElasticNet(alpha=a, l1_ratio=r)
        elastic.fit(X_train, y_train)
        y_pred = elastic.predict(X_test)
        scores.append([a,r, mean_absolute_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','l1_ratio', 'error'])
df_scores.sort_values('error')

Classification

In [ ]:
dum_hr = pd.get_dummies(hr, drop_first=True)
X = dum_hr.drop('left', axis=1)
y = dum_hr['left']

In [ ]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred_prob = lr.predict_proba(X_test)

solvers=['lbfgs','newton-cg', 'newton-cholesky', 'sag', 'saga']
Cs = [0.1, 1, 10, 100]
lr_scores = []

for c in tqdm(Cs, desc="Hyperparameter Tuning (Logistic Regression)"):
    for s in solvers:
        lr = LogisticRegression(solver=s,C=c)
        lr.fit(X_tran_train, y_train)
        y_pred_proba = lr.predict_proba(X_test_trans)
        score = log_loss(y_test, y_pred_proba)
        lr_scores.append([c,s, score])

df_lr_scores = pd.DataFrame(lr_scores, columns=['C', 'Solver','Log_Loss'])
print(df_lr_scores.sort_values('Log_Loss'))

# KNN - Scaling is IMP (ANY TYPE)
Ks = [1,2,3,4,5,6,7,8,9,10]
scores = []
for k in Ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    scores.append([k, accuracy_score( y_test, y_pred )])
df_scores = pd.DataFrame( scores, columns=['k', 'score'] )
df_scores.sort_values('score', ascending=False)

#SVM
Cs = np.linspace(0.001, 5, 20)
Gs = np.linspace(0.001, 5, 20) 
scores = []
for c in Cs:
    svm = SVC(kernel='linear', C=c) # kernel {poly:degree , rbf:gamma}
    svm.fit(X_train, y_train)
    y_pred = svm.predict(X_test)
    scores.append([c, f1_score(y_test, y_pred, pos_label='present')] )

df_scores = pd.DataFrame( scores, columns=['C', 'score'] )
df_scores.sort_values( 'score', ascending=False )

#NB
nb = GaussianNB()
nb.fit(X_train, y_train )
y_pred = nb.predict(X_test)
print(classification_report(y_test, y_pred))


disp = ConfusionMatrixDisplay( confusion_matrix(y_test, y_pred) )
disp.plot()
plt.show()

DCT and Enseamble

In [ ]:
X = p_df[['x1','x2']] ; y = p_df['y']
dtc = DecisionTreeClassifier(random_state=24)
dtc.fit(X, y)

#To plot DCT
plt.figure(figsize=(15,10))
plot_tree(dtc,feature_names=list(X.columns), class_names=['0','1'], filled=True,fontsize=18)
plt.show()

depths = [3,4,5,6,7,8,9, 10, 11, None]
leaves = [1,50, 75, 100, 150]
splits = [2,50, 75, 100, 150]
scores = []
for d in depths:
    for l in leaves:
        for s in splits:
            dtc = DecisionTreeClassifier(random_state=25, max_depth=d,
                                         min_samples_leaf=l, min_samples_split=s)
            dtc.fit(X_train_trns, y_train)
            y_pred = dtc.predict(X_test_trns)
            scores.append([d,l,s, f1_score(y_test, y_pred, pos_label=1 )] )
df_scores = pd.DataFrame( scores, columns=['depth','leaf','split','score'] )
df_scores.sort_values( 'score', ascending=False )

#To plot FEATURE IMPORTANCE GRAPH
df_imp = pd.DataFrame({'feature':X.columns,'importance':best_model.feature_importances_})
plt.figure(figsize=(10, 6))
plt.barh(df_imp['feature'], df_imp['importance'], color='skyblue')
plt.title('Feature Importances')
plt.show()

In [ ]:
#Voting
dtc1 = DecisionTreeClassifier(random_state=25)
dtc2 = DecisionTreeClassifier(random_state=25, max_depth=3)
knn1 = KNeighborsClassifier(n_neighbors=5)
knn2 = KNeighborsClassifier(n_neighbors=3)
nb = GaussianNB()
voting = VotingClassifier(estimators=[('TREE1',dtc1),('TREE2',dtc2),
                                      ('KNN1',knn1),('KNN2',knn2),
                                      ('NB',nb)]) #voting= soft , also wieghts can be adjusted(weights=[4, 2.5, 1, 1, 0]))
voting.fit(X_train, y_train)
y_pred = voting.predict(X_test)
print( classification_report(y_test, y_pred) )

#evalution of each estimator
for i in range(len(voting.estimators_)):
    print("Estimator: ", voting.estimators_[i])
    print("Accuracy Score = ", accuracy_score(y_test, voting.estimators_[i].predict(X_test)))

In [ ]:
#Bagging
dtc = DecisionTreeClassifier(random_state=25)
knn = KNeighborsClassifier()
nb = GaussianNB()
lr = LogisticRegression()

est_list = [nb, dtc, knn, lr]
n_est = [10, 15, 25, 50]
scores = []
for e in tqdm(est_list):
    for n in n_est:
        bagg = BaggingClassifier(random_state=25, n_estimators=n, estimator=e )
        bagg.fit(X_train, y_train)
        y_pred_prob = bagg.predict_proba(X_test)
        scores.append([e, n, log_loss(y_test, y_pred_prob)])
df_scores = pd.DataFrame( scores, columns=['Estimator','B-Samples','score'] )
df_scores.sort_values('score')

#RF
rf = RandomForestClassifier(random_state=25)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print( classification_report(y_test, y_pred) )

features = [2,3,4,5,6,7,8,9,10]
scores = []
for f in features:
    rf = RandomForestClassifier(random_state=25, max_features=f)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)
    scores.append([f, accuracy_score(y_test, y_pred)] )
df_scores = pd.DataFrame( scores, columns=['features','score'] )
df_scores.sort_values('score', ascending=False)

In [ ]:
#Boosting

#ADABOOST
from sklearn.ensemble import AdaBoostClassifier

ests = [dtc, nb, lr]
n_ests = [10, 25, 35, 60]
scores = []
for e in tqdm( ests ):
    for n in n_ests:
        ada = AdaBoostClassifier(estimator=e, n_estimators=n, random_state=25)
        ada.fit(X_train, y_train)
        y_pred_prob = ada.predict_proba(X_test)
        scores.append([e,n, log_loss(y_test, y_pred_prob) ])
df_scores = pd.DataFrame( scores, columns=['estimator','n_estimators','score'] )
df_scores.sort_values( 'score' )

#GRADBOOST
from sklearn.ensemble import GradientBoostingClassifier

l_rates = np.linspace(0.01, 0.8, 20)
n_est = [50, 100, 200]
depths = [3, 5, None]
scores = []
for r in tqdm(rates):
    for n in n_est:
        for d in depths:
            gbm = GradientBoostingClassifier(random_state=25,n_estimators=n,
                                             max_depth=d, learning_rate=r)
            gbm.fit(X_train, y_train)
            y_pred_prob = gbm.predict_proba(X_test)
            scores.append( [r, n, d, log_loss(y_test, y_pred_prob)] )
df_scores = pd.DataFrame( scores, columns=['rate','n_est','depth','score'] )
df_scores.sort_values( 'score', ascending=True )

from xgboost import XGBClassifier
rates = np.linspace(0.01, 0.8, 20)
n_est = [50, 100, 200]
depths = [3, 5, None]
scores = []
for r in tqdm(rates):
    for n in n_est:
        for d in depths:
            xgbm = XGBClassifier(random_state=25,n_estimators=n,
                                             max_depth=d, learning_rate=r)
            xgbm.fit(X_train, y_train)
            y_pred_prob = gbm.predict_proba(X_test)
            scores.append( [r, n, d, log_loss(y_test, y_pred_prob)] )
df_scores = pd.DataFrame( scores, columns=['rate','n_est','depth','score'] )
df_scores.sort_values( 'score', ascending=True )

from lightgbm import LGBMClassifier
rates = np.linspace(0.01, 0.8, 20)
n_est = [50, 100, 200]
depths = [3, 5, None]
scores = []
for r in tqdm(rates):
    for n in n_est:
        for d in depths:
            lgbm = LGBMClassifier(random_state=25,n_estimators=n,verbose=-1, 
                                             max_depth=d, learning_rate=r)
            lgbm.fit(X_train, y_train)
            y_pred_prob = gbm.predict_proba(X_test)
            scores.append( [r, n, d, log_loss(y_test, y_pred_prob)] )
df_scores = pd.DataFrame( scores, columns=['rate','n_est','depth','score'] )
df_scores.sort_values( 'score', ascending=True )

from catboost import CatBoostClassifier

rates = np.linspace(0.01, 0.8, 20)
n_est = [50, 100, 200]
depths = [3, 5, None]
scores = []
for r in tqdm(rates):
    for n in n_est:
        for d in depths:
            gbm = CatBoostClassifier(random_state=25,n_estimators=n,verbose=0, 
                                     max_depth=d, learning_rate=r)
            gbm.fit(X_train, y_train)
            y_pred_prob = gbm.predict_proba(X_test)
            scores.append( [r, n, d, log_loss(y_test, y_pred_prob)] )
df_scores = pd.DataFrame( scores, columns=['rate','n_est','depth','score'] )
df_scores.sort_values( 'score', ascending=True )

In [ ]:
#STACKING
base_learners = [
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('log_reg', LogisticRegression(max_iter=1000)),
    ('gnb', GaussianNB()),
    ('dt', DecisionTreeClassifier(random_state=42))
]

meta_learner = RandomForestClassifier()


stacking_model = StackingClassifier(
    estimators=base_learners,
    final_estimator=meta_learner,
    cv=5
)


stacking_model.fit(X_train, y_train)
y_pred = stacking_model.predict(X_test)

print(accuracy_score(y_test, y_pred))

# Stacking Regressor
base_learners = [
    ('rf', RandomForestRegressor(n_estimators=100, random_state=42)),
    ('linear', LinearRegression()),
    ('dt', DecisionTreeRegressor(random_state=42)),
    ('knn', KNeighborsRegressor(n_neighbors=5))
]


meta_learner = Ridge(alpha=1.0)

stacking_regressor = StackingRegressor(
    estimators=base_learners,
    final_estimator=meta_learner
)


stacking_regressor.fit(X_train, y_train)
y_pred = stacking_regressor.predict(X_test)


rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"Stacking Regressor RMSE: {rmse:.4f}")
print(f"Stacking Regressor R^2 Score: {r2:.4f}")

In [ ]:
#K-FOLD
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

lr = LinearRegression()
kfold = KFold(n_splits=5, shuffle=True, random_state=25)
next(iter(kfold.split(pizza)))

lr = LogisticRegression()
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=25)
results = cross_val_score(lr, X, y, cv=kfold) # defaults to accuracy
print( results.mean() )

solvers = ['lbfgs','liblinear','newton-cg','newton-cholesky','sag','saga']
Cs = np.linspace(0.001, 4, 20)
scores = []
for s in solvers:
    for c in Cs:
        lr = LogisticRegression(solver=s, C=c, random_state=25)
        results = cross_val_score(lr, X, y, cv=kfold, scoring='roc_auc') 
        scores.append([s , c ,np.mean(results)] )

In [ ]:
#Grid Search
X = concrete.drop('Strength', axis=1)
y = concrete['Strength']

lr = LogisticRegression()
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=25)
params = {'solver': ['lbfgs','liblinear','newton-cg','newton-cholesky','sag','saga'],
          'C': np.linspace(0.001, 4, 20)}
gcv = GridSearchCV(lr, param_grid=params, cv=kfold, scoring='roc_auc')
gcv.fit(X,y)

print( gcv.best_params_ )
print(gcv.best_score_)

rf = RandomForestRegressor(random_state=25)
rf.get_params()
params = {'max_features':[3,4,5,6,7], 'min_samples_split':[2,5,10,20],
          'max_depth':[None, 3, 5], 'min_samples_leaf':[1,5,10,20]}
kfold = KFold(n_splits=5, shuffle=True, random_state=25)
gcv = GridSearchCV(rf, param_grid=params, cv=kfold, scoring='r2', verbose=3)
gcv.fit(X, y)

Clustering

In [ ]:
from scipy.cluster.hierarchy import linkage, dendrogram
import seaborn as sns
import matplotlib.pyplot as plt

#LINKAGE GRAPH
scaler = StandardScaler().set_output(transform='pandas')
df_scaled = scaler.fit_transform(df)
link = "ward"
mergings = linkage(df_scaled,method=link)
dendrogram(mergings, labels=list(df_scaled.index))
plt.title(link+" linkage")
plt.show()

from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

clust = AgglomerativeClustering(n_clusters=2)
clust.fit(df_scaled)
clust.labels_

df_copy = df.copy()
df_copy['label'] = clust.labels_
df_copy.sort_values('label')

clusters = [2,3,4,5,6,7]
linkages = ['ward','single','complete','average']
scores = []
for c in clusters:
    for l in linkages:
        clust = AgglomerativeClustering(n_clusters=c, linkage=l )
        clust.fit(df_scaled)
        scores.append([c, l,silhouette_score(df_scaled, clust.labels_)])
df_scores = pd.DataFrame( scores, columns=['clusters','linkage' ,'score'] )
df_scores.sort_values('score', ascending=False)

In [ ]:
#K-MENAS
from sklearn.cluster import KMeans

clust = KMeans(random_state=25, n_clusters=3)
clust.fit(milk_scaled)
clust.labels_

wss = []
for i in range(2, 11):
    clust = KMeans(random_state=25, n_clusters=i)
    clust.fit(milk_scaled)
    wss.append([i, clust.inertia_] )
df_wss = pd.DataFrame( wss, columns=['clusters','wss'] )
plt.scatter(df_wss['clusters'], df_wss['wss'])
plt.plot( df_wss['clusters'], df_wss['wss'] )
plt.xlabel("Clusters")
plt.ylabel("WSS")
plt.title("Scree Plot")
plt.show()

#silhouette_score
scores = []
for i in range(2, 11):
    clust = KMeans(random_state=25, n_clusters=i)
    clust.fit(milk_scaled)
    scores.append([i, silhouette_score(milk_scaled, clust.labels_)] )
df_score = pd.DataFrame( scores, columns=['clusters','score'] )
df_score.sort_values('score', ascending=False)

In [ ]:
#DBSCAM

clust = DBSCAN(eps=0.6, min_samples=2)
clust.fit(milk_scaled)
clust.labels_

inliers = milk_scaled.copy()
inliers['label'] = clust.labels_
inliers = inliers[inliers['label']!=-1]
silhouette_score(inliers.iloc[:,:-1], inliers['label'])

epsilons = [0.2, 0.4, 0.6, 0.8, 1, 1.2]
min_pcts = [2, 3, 4, 5]
scores = []
for e in epsilons:
    for m in min_pcts:
        clust = DBSCAN(eps=e, min_samples=m)
        clust.fit(milk_scaled)       
        inliers = milk_scaled.copy()
        inliers['label'] = clust.labels_
        inliers = inliers[inliers['label']!=-1]
        # len( np.unique( inliers['label'] )) are the number of clusters
        # getting formed
        if len( np.unique( inliers['label'] )) >= 2:
            scores.append([e, m, silhouette_score(inliers.iloc[:,:-1], inliers['label'])])
df_scores = pd.DataFrame(scores, columns=['eps','min','score'])
df_scores.sort_values('score', ascending=False)

In [ ]:
#PCA
milk = pd.read_csv("milk.csv", index_col=0)
scaler = StandardScaler().set_output(transform='pandas')
milk_scaled = scaler.fit_transform(milk)

prcomp = PCA().set_output(transform='pandas')
pc_data = prcomp.fit_transform(milk_scaled)
pc_data.var()

values, vectors = np.linalg.eig(milk_scaled.cov())
print("Eigen Values: ", values)
prcomp.components_

#PCA plot
model = pca()
results = model.fit_transform(milk_scaled,
                              col_labels=milk.columns,
                              row_labels=list(milk.index))
model.biplot(label=True,legend=True)
for i in np.arange(0, milk.shape[0] ):
    plt.text(pc_data.values[i,0], 
             pc_data.values[i,1], 
             list(milk.index)[i])
plt.show()

prcomp.explained_variance_
prcomp.explained_variance_ / np.sum(prcomp.explained_variance_)  #explained_variance_ratio_
prcomp.explained_variance_ratio_

prcomp.explained_variance_ratio_*100 #percent of prcomp.explained_variance_ratio

np.cumsum(prcomp.explained_variance_ratio_*100)  #cummulative sum of explained_variance_ratio

#example of training model on PCA data
prcomp = PCA().set_output(transform='pandas')
X_trn_pca = prcomp.fit_transform(X_train)
X_trn_pca = X_trn_pca.iloc[:,:2]   # 2 Components
X_tst_pca = prcomp.transform(X_test)
X_tst_pca = X_tst_pca.iloc[:,:2]
svm = SVC(kernel='linear')
svm.fit(X_trn_pca, y_train)
y_pred = svm.predict(X_tst_pca)
print( classification_report(y_test, y_pred) )

# trying with diff size of C 
comps = np.arange(2, 50)
scores = []
for c in comps:
    X_trn_pca = prcomp.fit_transform(X_train)
    X_trn_pca = X_trn_pca.iloc[:,:c]
    X_tst_pca = prcomp.transform(X_test)
    X_tst_pca = X_tst_pca.iloc[:,:c]
    svm = SVC(kernel='linear')
    svm.fit(X_trn_pca, y_train)
    y_pred = svm.predict(X_tst_pca)
    scores.append([c, accuracy_score(y_test, y_pred) ])
df_scores = pd.DataFrame(scores, columns=['comps', 'score'])
df_scores.sort_values(['score','comps'], ascending=[False, True])

In [ ]:
from sklearn.manifold import TSNE
tsne = TSNE(random_state=25).set_output(transform='pandas')
X_tsne = tsne.fit_transform(X)
tsne_data = X_tsne.copy()
tsne_data['Class'] = y
sns.scatterplot( data=tsne_data, x='tsne0',y='tsne1', hue='Class' )
plt.title("Using t-SNE")
plt.show()

#with scaling
scaler = StandardScaler().set_output(transform='pandas')
X_scl = scaler.fit_transform(X)
tsne = TSNE(random_state=25,perplexity=45).set_output(transform='pandas')
X_tsne = tsne.fit_transform(X_scl)
tsne_data = X_tsne.copy()
tsne_data['Class'] = y
sns.scatterplot( data=tsne_data, x='tsne0',y='tsne1', hue='Class' )
plt.title("Using t-SNE")
plt.show()